// Auto generated by System, don't modify this file
package api

func InitApiService() {

	var service *ApiService

	GApiServices = make(map[string]*ApiService, 10000)

	// --------------------
	// for APIAccountLogOut
	// --------------------
	service = new(ApiService)
	service.Name = "APIAccountLogOut"
	service.Handler = APIAccountLogOut
	GApiServices["octlink.rstore.center.account.APIAccountLogOut"] = service

	// --------------------
	// for APIAddAccount
	// --------------------
	service = new(ApiService)
	service.Name = "APIAddAccount"
	service.Handler = APIAddAccount
	GApiServices["octlink.rstore.center.account.APIAddAccount"] = service

	// --------------------
	// for APIDeleteAccount
	// --------------------
	service = new(ApiService)
	service.Name = "APIDeleteAccount"
	service.Handler = APIDeleteAccount
	GApiServices["octlink.rstore.center.account.APIDeleteAccount"] = service

	// --------------------
	// for APILoginByAccount
	// --------------------
	service = new(ApiService)
	service.Name = "APILoginByAccount"
	service.Handler = APILoginByAccount
	GApiServices["octlink.rstore.center.account.APILoginByAccount"] = service

	// --------------------
	// for APIResetAccountPassword
	// --------------------
	service = new(ApiService)
	service.Name = "APIResetAccountPassword"
	service.Handler = APIResetAccountPassword
	GApiServices["octlink.rstore.center.account.APIResetAccountPassword"] = service

	// --------------------
	// for APIShowAccount
	// --------------------
	service = new(ApiService)
	service.Name = "APIShowAccount"
	service.Handler = APIShowAccount
	GApiServices["octlink.rstore.center.account.APIShowAccount"] = service

	// --------------------
	// for APIShowAccountList
	// --------------------
	service = new(ApiService)
	service.Name = "APIShowAccountList"
	service.Handler = APIShowAccountList
	GApiServices["octlink.rstore.center.account.APIShowAccountList"] = service

	// --------------------
	// for APIShowAllAccount
	// --------------------
	service = new(ApiService)
	service.Name = "APIShowAllAccount"
	service.Handler = APIShowAllAccount
	GApiServices["octlink.rstore.center.account.APIShowAllAccount"] = service

	// --------------------
	// for APIUpdateAccount
	// --------------------
	service = new(ApiService)
	service.Name = "APIUpdateAccount"
	service.Handler = APIUpdateAccount
	GApiServices["octlink.rstore.center.account.APIUpdateAccount"] = service

	// --------------------
	// for APIUpdateAccountPassword
	// --------------------
	service = new(ApiService)
	service.Name = "APIUpdateAccountPassword"
	service.Handler = APIUpdateAccountPassword
	GApiServices["octlink.rstore.center.account.APIUpdateAccountPassword"] = service
}
