// Auto generated by System, don't modify this file
package api

func InitApiService() {

	var service *ApiService

	GApiServices = make(map[string]*ApiService, 10000)

	// --------------------
	// for APIAddImage
	// --------------------
	service = new(ApiService)
	service.Name = "APIAddImage"
	service.Handler = APIAddImage
	GApiServices["octlink.rstore.center.images.APIAddImage"] = service

	// --------------------
	// for APIDeleteImage
	// --------------------
	service = new(ApiService)
	service.Name = "APIDeleteImage"
	service.Handler = APIDeleteImage
	GApiServices["octlink.rstore.center.images.APIDeleteImage"] = service

	// --------------------
	// for APIShowAllImages
	// --------------------
	service = new(ApiService)
	service.Name = "APIShowAllImages"
	service.Handler = APIShowAllImages
	GApiServices["octlink.rstore.center.images.APIShowAllImages"] = service

	// --------------------
	// for APIShowImage
	// --------------------
	service = new(ApiService)
	service.Name = "APIShowImage"
	service.Handler = APIShowImage
	GApiServices["octlink.rstore.center.images.APIShowImage"] = service

	// --------------------
	// for APIUpdateImage
	// --------------------
	service = new(ApiService)
	service.Name = "APIUpdateImage"
	service.Handler = APIUpdateImage
	GApiServices["octlink.rstore.center.images.APIUpdateImage"] = service
}
